export const userInputs = [
  {
    id: 1,
    label: "Fullname",
    type: "text",
    placeholder: "John Doe",
    name: "fullname",
  },
  {
    id: 2,
    label: "Business",
    type: "text",
    placeholder: "John Business Center",
  },
  {
    id: 3,
    label: "Email",
    type: "mail",
    placeholder: "john_doe@gmail.com",
  },
  {
    id: 4,
    label: "Phone",
    type: "text",
    placeholder: "+1 234 567 89",
  },
  {
    id: 5,
    label: "Password",
    type: "password",
  },
  {
    id: 6,
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
  },
  {
    id: 7,
    label: "Country",
    type: "text",
    placeholder: "USA",
  },
];
export const productInputs = [
  {
    id: 1,
    label: "Name",
    type: "text",
    placeholder: "Apple Macbook Pro",
    name: "name",
  },
  {
    id: 2,
    label: "Description",
    type: "textarea",
    placeholder: "Description",
    name: "description",
  },
  {
    id: 3,
    label: "Category",
    type: "text",
    placeholder: "Electronics",
    name: "category",
  },
  {
    id: 4,
    label: "Subcategory",
    type: "text",
    placeholder: "Computers and Laptops",
    name: "subcategory",
  },
  {
    id: 5,
    label: "Price",
    type: "number",
    placeholder: "100",
    name: "price",
  },
  {
    id: 6,
    label: "Discount_Price",
    type: "number",
    placeholder: "90",
    name: "discount_price",
  },
  {
    id: 7,
    label: "Stock",
    type: "number",
    placeholder: "5",
    name: "stock",
  },
  {
    id: 8,
    label: "Shop",
    type: "text",
    placeholder: "John Business Center",
    name: "shop",
  },
  {
    id: 9,
    label: "Condition",
    type: "text",
    placeholder: "Brand New",
    name: "condition",
  },
  {
    id: 10,
    label: "Brand",
    type: "text",
    placeholder: "Apple",
    name: "brand",
  },
];
